### ISSUE TITLE
Clarify performance

### ISSUE THREAD

**Issue by fulldecent** [savaslabs/squabble#22]
This issue is a comment on http://savaslabs.com/2016/04/20/squabble-comments.html but since comments there are closed I'll discuss here.

I noticed:

>  the `api/comments/count` call takes ~84 ms.

This scares me -- ten simultaneous page loads and your site now loads in > one second.

Could you please clarify your site metrics and maybe clarify what size sites this product is designed for?

**Comment by kostajh** [comment]
@fulldecent sorry for the late reply.

We use this comment server app for our blog and it's worked well for us. I'm not sure how well it would work in other use cases.

I would call the `api/comments/count` endpoint in an asynchronous manner, so that your page can load, then you can populate it with data returned from the comment server.

**Comment by fulldecent** [comment]
Sounds good, thank you for clarifying.
